baseURL = 'https://ddtpow2.github.io/sharing-site/'
languageCode = 'zh-CN'
title = "敌敌畏的菜园子"

theme = "PaperMod"

enableGitInfo = true

[params]
  ShowPostDate = true
  ShowLastMod = true
  ShowReadingTime = true
  ShowWordCount = true

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']
